/**
 * Fluent theme bridge: 10 pre-generated Fluent v9 Theme objects (5 accent x light/dark),
 * derived offline from the 5 existing accent hex anchors in theme-store.ts.
 *
 * Per D-01/D-02 (39-CONTEXT.md): this is static data computed once at module load,
 * cached in a Map, and NEVER recomputed from runtime CSS variables. The 16-stop
 * BrandVariants ramp is generated by a small in-module HSL-lightness-stepping
 * function -- no color-math library dependency is added.
 *
 * The 5 anchor hexes below are copied literally from
 * `frontend/src/stores/theme-store.ts`'s `ACCENT_COLORS` (do not import them at
 * runtime -- these must be static, offline data per D-02). If theme-store.ts's
 * accent hexes ever change, this file's anchors must be manually re-synced.
 */
import {
  createDarkTheme,
  createLightTheme,
  type BrandVariants,
  type Theme,
} from "@fluentui/react-components";

export type FluentThemeMode = "light" | "dark";
export type FluentAccentColor = "blue" | "teal" | "purple" | "rose" | "amber";

/** Copied from theme-store.ts ACCENT_COLORS -- re-sync manually if those hexes change. */
const ACCENT_ANCHOR_HEX: Record<FluentAccentColor, string> = {
  blue: "#1E40AF",
  teal: "#0D9488",
  purple: "#7C3AED",
  rose: "#BE185D",
  amber: "#B45309",
};

/** Fluent's 16 fixed ramp stops, in ascending order. Anchor hex sits at stop 80. */
const RAMP_STOPS = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160] as const;
const ANCHOR_STOP = 80;
const RAMP_MIN_STOP = 10;
const RAMP_MAX_STOP = 160;

interface HSL {
  h: number;
  s: number;
  l: number;
}

function hexToHsl(hex: string): HSL {
  const normalized = hex.replace("#", "");
  const r = parseInt(normalized.slice(0, 2), 16) / 255;
  const g = parseInt(normalized.slice(2, 4), 16) / 255;
  const b = parseInt(normalized.slice(4, 6), 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  let h = 0;
  let s = 0;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r:
        h = ((g - b) / d + (g < b ? 6 : 0)) * 60;
        break;
      case g:
        h = ((b - r) / d + 2) * 60;
        break;
      default:
        h = ((r - g) / d + 4) * 60;
        break;
    }
  }

  return { h, s, l: l * 100 };
}

function hslToHex({ h, s, l }: HSL): string {
  const sNorm = s / 100;
  const lNorm = l / 100;
  const c = (1 - Math.abs(2 * lNorm - 1)) * sNorm;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = lNorm - c / 2;

  let r = 0;
  let g = 0;
  let b = 0;

  if (h < 60) {
    r = c;
    g = x;
  } else if (h < 120) {
    r = x;
    g = c;
  } else if (h < 180) {
    g = c;
    b = x;
  } else if (h < 240) {
    g = x;
    b = c;
  } else if (h < 300) {
    r = x;
    b = c;
  } else {
    r = c;
    b = x;
  }

  const toHex = (v: number) =>
    Math.round((v + m) * 255)
      .toString(16)
      .padStart(2, "0");

  return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

/**
 * Builds a 16-stop BrandVariants ramp anchored on `anchorHex` at stop 80 (Fluent's
 * "primary" convention). Lightness steps monotonically darker below stop 80 and
 * lighter above stop 80, using plain HSL-lightness arithmetic (no library).
 */
function buildBrandRamp(anchorHex: string): BrandVariants {
  const anchorHsl = hexToHsl(anchorHex);
  const ramp = {} as Record<(typeof RAMP_STOPS)[number], string>;

  const darkestL = 4; // stop 10 -> near-black
  const lightestL = 96; // stop 160 -> near-white

  for (const stop of RAMP_STOPS) {
    if (stop === ANCHOR_STOP) {
      ramp[stop] = anchorHex;
      continue;
    }

    let l: number;
    if (stop < ANCHOR_STOP) {
      // Steps 10..70 interpolate from darkest to just-above-darkest at the anchor.
      const t = (stop - RAMP_MIN_STOP) / (ANCHOR_STOP - RAMP_MIN_STOP);
      l = darkestL + t * (anchorHsl.l - darkestL);
    } else {
      // Steps 90..160 interpolate from just-below-lightest up to lightest.
      const t = (stop - ANCHOR_STOP) / (RAMP_MAX_STOP - ANCHOR_STOP);
      l = anchorHsl.l + t * (lightestL - anchorHsl.l);
    }

    ramp[stop] = hslToHex({ h: anchorHsl.h, s: anchorHsl.s, l: clamp(l, 0, 100) });
  }

  return ramp as BrandVariants;
}

const RAMPS: Record<FluentAccentColor, BrandVariants> = {
  blue: buildBrandRamp(ACCENT_ANCHOR_HEX.blue),
  teal: buildBrandRamp(ACCENT_ANCHOR_HEX.teal),
  purple: buildBrandRamp(ACCENT_ANCHOR_HEX.purple),
  rose: buildBrandRamp(ACCENT_ANCHOR_HEX.rose),
  amber: buildBrandRamp(ACCENT_ANCHOR_HEX.amber),
};

const THEME_CACHE = new Map<string, Theme>();

/**
 * Returns one of 10 cached Theme objects (5 accent x light/dark). Themes are built
 * lazily on first access per key and cached in a module-level Map -- never
 * recomputed at runtime.
 */
export function getFluentTheme(mode: FluentThemeMode, accent: FluentAccentColor): Theme {
  const key = `${mode}:${accent}`;
  const cached = THEME_CACHE.get(key);
  if (cached) {
    return cached;
  }

  const ramp = RAMPS[accent];
  const theme = mode === "dark" ? createDarkTheme(ramp) : createLightTheme(ramp);
  THEME_CACHE.set(key, theme);
  return theme;
}

/** Exported for test assertions only (round-trip anchor-hex verification). */
export const __TEST_ONLY__ = { ACCENT_ANCHOR_HEX, RAMPS, ANCHOR_STOP };
