import { describe, it, expect, vi, afterEach } from "vitest";
import { render, screen, cleanup } from "@testing-library/react";
import { createRef } from "react";
import { FluentProvider, webLightTheme } from "@fluentui/react-components";

import { Button } from "./button";

function renderWithProvider(ui: React.ReactElement) {
  return render(<FluentProvider theme={webLightTheme}>{ui}</FluentProvider>);
}

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("Button", () => {
  // Test 1
  it("renders Fluent Button with appearance='primary' for variant='default'", () => {
    renderWithProvider(<Button variant="default">Click</Button>);
    const btn = screen.getByRole("button", { name: "Click" });
    expect(btn).toHaveAttribute("data-slot", "button");
    // Fluent's primary appearance applies its own root class; assert it renders
    // as a native button and carries no destructive override class.
    expect(btn.tagName).toBe("BUTTON");
  });

  // Test 2
  it("renders appearance='outline' size='large' for variant='outline' size='lg'", () => {
    renderWithProvider(
      <Button variant="outline" size="lg">
        Outline
      </Button>,
    );
    const btn = screen.getByRole("button", { name: "Outline" });
    expect(btn).toBeInTheDocument();
    expect(btn).toHaveAttribute("data-slot", "button");
  });

  // Test 3
  it("applies the Griffel destructive override producing the pre-migration background color", () => {
    renderWithProvider(<Button variant="destructive">Delete</Button>);
    const btn = screen.getByRole("button", { name: "Delete" });
    // jsdom's `getComputedStyle` does not reliably resolve cascade winners
    // across Griffel's dynamically-inserted atomic <style> buckets (its CSSOM
    // application order is not guaranteed to mirror real-browser rendering),
    // so assert directly against the CSSOM rule generated by
    // `useDestructiveStyles().root` instead: confirm one of the classes Griffel
    // attached to this button resolves, via the actual injected stylesheet
    // rule, to the exact pre-migration `var(--destructive)` value (D-04 --
    // byte-identical, not merely visually close).
    const classNames = Array.from(btn.classList);
    const matchingRule = Array.from(document.styleSheets)
      .flatMap((sheet) => {
        try {
          return Array.from(sheet.cssRules);
        } catch {
          return [];
        }
      })
      .find(
        (rule): rule is CSSStyleRule =>
          rule instanceof CSSStyleRule &&
          classNames.some((cls) => rule.selectorText === `.${cls}`) &&
          rule.cssText.includes("background-color: var(--destructive)"),
      );
    expect(matchingRule).toBeDefined();
  });

  // Test 4
  it("defaults to appearance='primary' size='medium' when no variant/size props given", () => {
    renderWithProvider(<Button>Default</Button>);
    const btn = screen.getByRole("button", { name: "Default" });
    expect(btn).toHaveAttribute("data-slot", "button");
  });

  // Test 5
  it('has data-slot="button" on the rendered root element', () => {
    renderWithProvider(<Button>Slot</Button>);
    expect(screen.getByRole("button")).toHaveAttribute("data-slot", "button");
  });

  // Test 6
  it("asChild renders a single <a> carrying className and props, not a nested button", () => {
    renderWithProvider(
      <Button asChild>
        <a href="/x">Link</a>
      </Button>,
    );
    const link = screen.getByRole("link", { name: "Link" });
    expect(link.tagName).toBe("A");
    expect(link).toHaveAttribute("data-slot", "button");
    expect(screen.queryByRole("button")).not.toBeInTheDocument();
  });

  // Test 7
  it("falls back to default render with a dev warning when asChild child cannot accept a ref", () => {
    const warnSpy = vi.spyOn(console, "warn").mockImplementation(() => {});
    renderWithProvider(<Button asChild>{"just a string" as unknown as React.ReactElement}</Button>);
    expect(warnSpy).toHaveBeenCalledWith(expect.stringContaining("asChild requires a single ref-forwarding child"));
    expect(screen.getByRole("button")).toBeInTheDocument();
  });

  // Test 8
  it("falls back to default render with a dev warning when asChild has multiple children", () => {
    const warnSpy = vi.spyOn(console, "warn").mockImplementation(() => {});
    renderWithProvider(
      <Button asChild>
        <>
          <span>One</span>
          <span>Two</span>
        </>
      </Button>,
    );
    expect(warnSpy).toHaveBeenCalledWith(expect.stringContaining("asChild requires a single ref-forwarding child"));
    expect(screen.getByRole("button")).toBeInTheDocument();
  });

  // Test 9
  it("forwards ref to the actual <button> DOM node when not asChild", () => {
    const ref = createRef<HTMLButtonElement>();
    renderWithProvider(<Button ref={ref}>Ref</Button>);
    expect(ref.current).not.toBeNull();
    expect(ref.current?.tagName).toBe("BUTTON");
    ref.current?.focus();
    expect(document.activeElement).toBe(ref.current);
  });
});
